name: Update Screener Results

on:
  schedule:
    - cron: "0 * * * *"   # Jede volle Stunde
  workflow_dispatch:       # Manuell startbar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Screener
        run: python scripts/screener.py

      - name: Commit and Push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/results.json
          git commit -m "Auto-update results"
          git push
